name: Update Leaderboard

on:
  push:
    branches:
      - main
    paths:
      - 'docs/leaderboard.csv'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: pip install pandas
    
    - name: Render leaderboard
      run: python competition/render_leaderboard.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add leaderboard/leaderboard.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update leaderboard"
        git pull origin main --rebase
        git push
